language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install --upgrade pip
  - pip install pytest pytest-cov -U
  - python setup.py develop
script:
  - pytest --cov=scikit_tt tests/
after_script:
  - bash <(curl -s https://codecov.io/bash)
